name: バグ報告
description: バグを発見された方はこちらへ
labels: [bug]
body:
  - type: textarea
    attributes:
      label: 概要
    validations:
      required: true
  - type: dropdown
    attributes:
      label: ブラウザ
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
        - その他
    validations:
      required: true
  - type: textarea
    attributes:
      label: 再現手順
